### ISSUE TITLE
How do inference?

### ISSUE THREAD

**Issue by cama36** [bxiang233/PanopticSegForLargeScalePointCloud#2]
Hello, thank you very much for your work. I noticed that when using eval.py, the data will also load semantic labels and instance labels. I think this part is only for evaluation, but when the data does not have this content, I modify this part of the code, and I will get surprising results. How can I do inference?

**Comment by bxiang233** [comment]
> Hello, thank you very much for your work. I noticed that when using eval.py, the data will also load semantic labels and instance labels. I think this part is only for evaluation, but when the data does not have this content, I modify this part of the code, and I will get surprising results. How can I do inference?

Hi, thanks for your interest in our work! Yes, the semantic labels and instance labels are for evaluation only. I think the easiest way to do the quick inference is by adding "fake labels". For example, all points assign instance labels with 0, and semantic labels with 0. Then you will not get reasonable value for evaluation metrics, but you could still get prediction and visualization output files. Hope it can solve your problem.

**Comment by cama36** [comment]
Thank you very much for your reply,I see.
